#Import libraries
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm, tree
import pandas as pd
import seaborn as sns
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt

#Get results from excel file generated by the api info colector
excel = input("Enter excel file address: ")
df = pd.read_excel(excel)

#Generate correlation matrix in orther to see most important values
corr = df.corr()
plt.figure(figsize=(16, 6))
heatmap = sns.heatmap(df.corr(), vmin=-1, vmax=1, annot=True)
heatmap.set_title('Correlation Heatmap', fontdict={'fontsize':18}, pad=12)

x_keep = ['Level', 'Minions', 'Jungle_minions',	'Kills', 'Assists',	'Deaths', 'Plates',	'Towers', 'Dragons', 'Heralds', 'Sight_wards', 'Control_wards', 'Gold_diff']
X = df[x_keep]
y = df["Win"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
model = RandomForestClassifier().fit(X_train, y_train)
y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))
